NUMPY LAB WORK ON JUPYTER NOTEBOOK

                            ASSIGNMENT
Q-1. Calculate the total revenue generated by two product categories in a store


In [7]:
import numpy as np

# Example data: quantities sold and prices for two product categories
quantities_category1 = np.array([10, 15, 20])  # Quantities sold for category 1
prices_category1 = np.array([100, 150, 200])   # Prices for category 1

quantities_category2 = np.array([5, 10, 15])   # Quantities sold for category 2
prices_category2 = np.array([200, 250, 300])   # Prices for category 2

# Calculate revenue for each category
revenue_category1 = np.sum(quantities_category1 * prices_category1)
revenue_category2 = np.sum(quantities_category2 * prices_category2)

# Calculate total revenue
total_revenue = revenue_category1 + revenue_category2

# Print the total revenue
print("Total revenue generated by two product categories:", total_revenue)


Total revenue generated by two product categories: 15250


Q-2. Calculate the profit made by a company


In [5]:
import numpy as np

# Example data: total revenue and total expenses
total_revenue = np.array([10000, 15000, 20000])  # Total revenue for different periods
total_expenses = np.array([7000, 8000, 12000])   # Total expenses for different periods

# Calculate profit for each period
profit = total_revenue - total_expenses

# Print the profit for each period
print("Profit for each period:", profit)

# Calculate and print the total profit
total_profit = np.sum(profit)
print("Total profit made by the company:", total_profit)

Profit for each period: [3000 7000 8000]
Total profit made by the company: 18000


Q-3.Determine which product in a store  are out of stock(quantity is 0)

In [8]:
import numpy as np

# Example data: product names and their quantities
product_names = np.array(["Product A", "Product B", "Product C", "Product D","Product E","Product F"])
inventory = np.array([10, 0, 5, 0,20,0])  # Quantities of each product

# Determine which products are out of stock
out_of_stock = product_names[inventory == 0]

# Print the out of stock products
print("Products out of stock:", out_of_stock)


Products out of stock: ['Product B' 'Product D' 'Product F']


Q-4. Calculate the total cost of items in a shopping cart,considering the quantity and price per item

In [9]:
import numpy as np

# Example data: quantities and prices of items in the shopping cart
quantities = np.array([2, 3, 4, 1])  # Quantities of each item
prices = np.array([10.0, 5.0, 8.0, 12.0])  # Prices per item

# Calculate the total cost for each item
total_cost_per_item = quantities * prices

# Calculate the total cost of the shopping cart
total_cost = np.sum(total_cost_per_item)
print("Total cost of items:", total_cost_per_item)
# Print the total cost
print("Total cost of items in the shopping cart:", total_cost)


Total cost of items: [20. 15. 32. 12.]
Total cost of items in the shopping cart: 79.0


                             LAB-2
Q-1. Convert the below list into numpy array then display the array                             

In [10]:
import numpy as np

# Input list
input_list = [1, 2, 3, 4, 5]

# Convert list to numpy array
output_array = np.array(input_list)

# Display the numpy array
print(output_array)


[1 2 3 4 5]


Q-2. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result

In [11]:
import numpy as np

# Input list
input_list = [1, 2, 3, 4, 5]

# Convert list to numpy array
output_array = np.array(input_list)

# Display the numpy array
print("Numpy array:", output_array)

# Display the first and last index
print("First element:", output_array[0])
print("Last element:", output_array[-1])

# Multiply each element by 2
multiplied_array = output_array * 2

# Display the result
print("Multiplied array:", multiplied_array)


Numpy array: [1 2 3 4 5]
First element: 1
Last element: 5
Multiplied array: [ 2  4  6  8 10]


                            LAB-3
Q-1. Write a NumPy program to create an array of 10 zeroes,10 ones and 10 fives.

In [12]:
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)

# Create an array of 10 ones
ones_array = np.ones(10)

# Create an array of 10 fives
fives_array = np.full(10, 5)

# Print the arrays
print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


Q-2. Write a NumPy program to create a 3*3 matrix with values ranging from 2 to 10

In [13]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

# Print the matrix
print("3x3 Matrix with values ranging from 2 to 10:")
print(matrix)


3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
